[package]
name = "engine"
version = "0.1.0"
edition = "2021"
description = "A powerful physics engine."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]